Added workaround mentioned in the bug -- Javascript version :)
dubzzz/protractor-move-async-await pull request #2
Opened 2018-05-06 16:10 UTC by Jayasankar-m

Added 2 files incorporating the workaround - MakeSequential in javascript

2018-05-06 16:18 UTC, Jayasankar-m reviewed
point to the spec file with the workaround

2018-05-06 16:59 UTC, dubzzz requested changes
Thanks a lot for this solution

I will merge it as soon as you provide a version with no logs and arrow functions (optional)

2018-05-06 16:59 UTC, dubzzz commented on test/async/spec.js
> +      .filter(MakeSequential(function(todo) {return todo.getText().then(label =>{console.log(label); return label.indexOf('#10') !== -1})}))
Would be great if you remove the console.log and switch to arrow function whenever possible

2018-05-07 07:34 UTC, Jayasankar-m reviewed
Removed console.log and added arrow functions as suggested

2018-05-07 07:34 UTC, merged

2018-05-07 07:35 UTC, dubzzz commented
Thanks a lot for the PR